/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./App.vue')['default']
    AppHome: typeof import('./views/AppHome/index.vue')['default']
    AppNotFound: typeof import('./views/AppNotFound/index.vue')['default']
    AppRecord: typeof import('./views/AppRecord/index.vue')['default']
    AppSelect: typeof import('./views/AppSelect/index.vue')['default']
    AppTeam: typeof import('./views/AppTeam/index.vue')['default']
    AppUpload: typeof import('./views/AppUpload/index.vue')['default']
    AppView: typeof import('./views/AppView/index.vue')['default']
    MyHeader: typeof import('./components/MyHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
