/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./App.vue')['default']
    AppHome: typeof import('./views/AppHome/index.vue')['default']
    AppNotFound: typeof import('./views/AppNotFound/index.vue')['default']
    AppRecord: typeof import('./views/AppRecord/index.vue')['default']
    AppSelect: typeof import('./views/AppSelect/index.vue')['default']
    Appteam: typeof import('./views/Appteam/index.vue')['default']
    AppTeam: typeof import('./views/AppTeam/index.vue')['default']
    AppUpload: typeof import('./views/AppUpload/index.vue')['default']
    AppView: typeof import('./views/AppView/index.vue')['default']
    copy: typeof import('./views/AppUpload/index copy.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    MyHeader: typeof import('./components/MyHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanButton: typeof import('vant/es')['Button']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanEmpty: typeof import('vant/es')['Empty']
  }
}
